src/apps/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('register/verify_code/', views.UserRegisterVerifyCodeView.as_view(), name='verify'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    # reset password
    path('forget-password/', views.ForgettingPasswordView.as_view(), name='forget_password'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='reset_password'),
    path("reset-password-done/", views.ResetPasswordDoneView.as_view(), name='reset_password_done'),
    # dashboard
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('edit-profile/', views.EditProfileView.as_view(), name='edit_profile'),
    # Address
    path('addresses/', views.AddressView.as_view(), name='addresses'),
    path('addresses/add/', views.AddAddressView.as_view(), name='add_addresses'),
    path('addresses/edit/<uuid:id>/', views.EditAddressView.as_view(), name='edit_addresses'),
    path('addresses/delete/<uuid:id>/', views.DeleteAddressView.as_view(), name='delete_addresses'),
    path('addresses/set-default/<uuid:id>/', views.SetDefaultAddressView.as_view(), name='set_default_addresses'),
    # Wash list
    path('washlist/', views.WashListView.as_view(), name='wash_list'),
    path('washlist/add-to-washlist/<int:id>/', views.AddWashListView.as_view(), name='add_wash_list'),
    # orders
    path('orders/', views.UserOrders.as_view(), name='user_orders'),
]

src/apps/basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.BasketSummaryView.as_view(), name='basket_summary'),
    path('basket-add/', views.BasketAddView.as_view(), name='basket_add'),
    path('basket-delete/', views.BasketDeleteView.as_view(), name='basket_delete'),
    path('basket-update/', views.BasketUpdateView.as_view(), name='basket_update'),
]

src/apps/catalogue/urls.py
from django.urls import path

from . import views

app_name = 'catalogue'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product-detail/<str:web_id>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('category/<slug:slug>/', views.CategoryListView.as_view(), name='category'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap

from apps.catalogue.sitemaps import StaticSitemapView, CategorySitemapView, ProductSitemapView

sitemaps = {
    'static': StaticSitemapView,
    'category': CategorySitemapView,
    'product': ProductSitemapView,
}

urlpatterns = [
    path('search/', include('apps.search.urls', namespace='search')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('robot.txt', include('robots.urls')),
    path('adminstartion@mohammadhssn78/', admin.site.urls),
    path('account/', include('apps.account.urls', namespace='account')),
    path('basket/', include('apps.basket.urls', namespace='basket')),
    path('checkout/', include('apps.checkout.urls', namespace='checkout')),
    path('oreders/', include('apps.orders.urls', namespace='orders')),
    path('', include('apps.catalogue.urls', namespace='catalogue')),

]

# if settings.DEBUG:
#     urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

src/apps/catalogue/views.py
from django.contrib.postgres.aggregates import ArrayAgg
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.core.cache import cache
from django.http import HttpResponse

from .models import ProductInventory, ProductTypeAttribute, Media, Category


class HomeView(View):
    template_name = 'catalogue/home.html'

    def get(self, request):
        products = ProductInventory.objects.prefetch_related('media_product_inventory').filter(is_active=True)
        return render(request, self.template_name, {'products': products})


class ProductDetailView(View):
    """
        Product detail view
        input: web_id product model
        get attribute name and value for product
        and use cache for cache set model ProductInventory and cache media product
    """

    template_name = 'catalogue/product_detail.html'

    def get(self, request, web_id=None):

        if cache.get(web_id):
            product_inventory = cache.get(web_id)
        else:
            try:
                product_inventory = ProductInventory.objects.filter(product__web_id=web_id)
                cache.set(web_id, product_inventory)
            except ProductInventory.DoesNotExist:
                return HttpResponse('this product dose not exists')

        # product_inventory = ProductInventory.objects.filter(product__web_id=web_id)
        # ===================================================================================================
        if request.GET:
            filter_arguments = []
            for value in request.GET.values():
                filter_arguments.append(value)

            # product = ProductInventory.objects.filter(product__web_id=web_id).filter(
            #     attribute_values__attribute_value__in=filter_arguments).annotate(
            #     num_tags=Count('attribute_values')).filter(num_tags=len(filter_arguments)).values(
            #     "id", "sku", "product__name", "store_price", "product_inventory__units").annotate(
            #     field_a=ArrayAgg("attribute_values__attribute_value")).get()

            product = product_inventory.filter(
                attribute_values__attribute_value__in=filter_arguments).annotate(
                num_tags=Count('attribute_values')).filter(num_tags=len(filter_arguments)).values(
                "id", "sku", "product__id", "product__name", "store_price", "product_inventory__units").annotate(
                field_a=ArrayAgg("attribute_values__attribute_value")).get()

        else:
            # product = ProductInventory.objects.filter(
            #     product__web_id=web_id).filter(is_default=True).values(
            #     "id", "sku", "product__id", "product__name", "store_price", "product_inventory__units").annotate(
            #     field_a=ArrayAgg("attribute_values__attribute_value")).get()

            product = product_inventory.filter(
                product__web_id=web_id).filter(is_default=True).values(
                "id", "sku", "product__id", "product__name", "store_price", "product_inventory__units").annotate(
                field_a=ArrayAgg("attribute_values__attribute_value")).get()
        # ===================================================================================================
        # must be Change
        web_id_image_key = f'{web_id}_image'
        if cache.get(web_id_image_key):
            product_image = cache.get(web_id_image_key)
        else:
            try:
                product_image = Media.objects.filter(
                    product_inventory__product__web_id=web_id)
                cache.set(web_id_image_key, product_image)
            except Media.DoesNotExist:
                return HttpResponse('this Media dose not exists')

        # product_image = Media.objects.filter(
        #     product_inventory__product__web_id=web_id)
        # ===================================================================================================
        # product_attribute_values = ProductInventory.objects.filter(product__web_id=web_id).distinct().values(
        #     "attribute_values__product_attribute__name", "attribute_values__attribute_value")

        product_attribute_values = product_inventory.filter(product__web_id=web_id).distinct().values(
            "attribute_values__product_attribute__name", "attribute_values__attribute_value")
        # ===================================================================================================
        product_type_attributes = ProductTypeAttribute.objects.filter(
            product_type__product_type__product__web_id=web_id).distinct().values("product_attribute__name")

        return render(request, self.template_name,
                      {'product': product, 'product_attribute_values': product_attribute_values,
                       'product_type_attributes': product_type_attributes, 'product_image': product_image})


class CategoryListView(View):
    """
        List of Category
        input: slug form model Category
        and get category and get products with filter by category instance
        and use paginator for show products (10 product every page)
    """

    template_name = 'catalogue/category.html'

    def get(self, request, slug=None):
        category = get_object_or_404(Category, slug=slug, is_active=True)
        products = ProductInventory.objects.is_default().filter(
            product__category__in=category.get_descendants(
                include_self=True)).distinct()

        paginator = Paginator(products, 10)  # Show 10 contacts per page.
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(request, self.template_name, {'category': category, 'page_obj': page_obj})

src/apps/catalogue/templates/catalogue/category.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}{% trans 'Products' %}{% endif %}
{% endblock %}
{% block content %}

    <div class="container" style="max-width: 1000px">
        <div class="col-12">
            <h1 class="h2">{{ category.name|title }}</h1>
        </div>
        <div class="col-12 d-flex justify-content-between">
            <div><b>{% trans 'Popular' %}</b> {% trans 'products purchased' %}</div>
        </div>
        <hr/>
    </div>
    <div class="container">
        <div class="row">
            <div class="album">
                {% if not page_obj %}
                    <div class="col-12">{% trans 'There are currently no products active' %} <a
                            href="{% url 'catalogue:home' %}">{% trans 'Home' %}</a>
                    </div>
                {% else %}
                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                        {% for product in page_obj %}
                            <div class="col">
                                <div class="card border-0">
                                    {% for image in product.media_product_inventory.all %}
                                        {% if image.is_feature %}
                                            <img class="img-fluid" src="{{ image.image.url }}"
                                                 alt="{{ image.alt_text }}">
                                        {% endif %}
                                    {% endfor %}
                                    <div class="card-body px-0">
                                        <p class="card-text">
                                            <a class="text-dark text-decoration-none"
                                               href="{{ product.product.get_absolute_url }}">{{ product.product.name }}</a>
                                        </p>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <small class="text-muted">£{{ product.store_price }}</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}

                <!-- Pager-->
                {% if page_obj.has_previous %}
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase"
                                                                    href="{% url 'catalogue:category' category.slug %}?page={{ page_obj.previous_page_number }}">
                        &rarr;</a></div><br><br><br>
                {% endif %}

                {% if page_obj.has_next %}
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase"
                                                                    href="{% url 'catalogue:category' category.slug %}?page={{ page_obj.next_page_number }}">
                        &larr;</a></div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

src/apps/catalogue/templates/catalogue/home.html
{% extends 'base.html' %}
{% load i18n %}


{% block title %}
    {% trans 'Store' %}
{% endblock %}

{% block content %}

    <div class="container">
        <div class="container">
            <div class="row">
                <div class="album py-5">
                    <div class="pb-3">
                        <h1 class="h3">{% trans 'Popular' %}</h1>
                    </div>
                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                        {% for product in products %}
                            <div class="col">
                                <div class="card border-0">

                                    {% for image in product.media_product_inventory.all %}
                                        {% if image.is_feature %}
                                            <a href="{{ product.product.get_absolute_url }}" target="_blank">
                                                <img class="img-fluid" src="{{ image.image.url }}"
                                                     alt="{{ image.alt_text }}"></a>
                                        {% endif %}
                                    {% endfor %}

                                    <div class="card-body px-0">
                                        <p class="card-text">
                                            <a class="text-dark text-decoration-none"
                                               href="{{ product.product.get_absolute_url }}">{{ product.product.name }}</a>
                                        </p>
                                        <div class="fw-bold">{{ product.store_price }} Toman</div>
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                            <div class="col-12">{% trans 'There are currently no products active' %}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/apps/catalogue/templates/catalogue/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block stylesheet %}{% static 'catalogue/css/catalogue.css' %}{% endblock %}

{% block title %}
    {% if product %}{{ product.title }}{% else %}{% trans 'Product' %}{% endif %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row g-3">
            <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
                <div class="d-grid gap-2">
                    <div class="d-flex d-flex-inline justify-content-between">
                        <div><span class="h3">{{ product.store_price }} Toman</span>
                            <p class="text-muted">{% trans 'includes tax' %}</p></div>
                        <div>
                            <label for="select">{% trans 'Qty' %}</label>
                            <select id="select" class="h6 store-select-dropdown">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </div>

                    </div>
                    <ul>
                        {% for p_attribute in product_type_attributes %}
                            <li class="text-capitalize">
                                {{ p_attribute.product_attribute__name }}
                                <ul>
                                    {% for p_attr_value in product_attribute_values %}
                                        {% if p_attr_value.attribute_values__product_attribute__name == p_attribute.product_attribute__name %}
                                            <li class="text-capitalize">
                                                {% if p_attr_value.attribute_values__attribute_value in product.field_a %}
                                                    <div id="target-{{ p_attr_value.attribute_values__attribute_value }}"
                                                         class="selected fw-bold"
                                                         data-attribute="{{ p_attribute.product_attribute__name }}"
                                                         value="{{ p_attr_value.attribute_values__attribute_value }}">{{ p_attr_value.attribute_values__attribute_value }}</div>
                                                {% else %}
                                                    <div id="target-{{ p_attr_value.attribute_values__attribute_value }}"
                                                         class=""
                                                         data-attribute="{{ p_attribute.product_attribute__name }}"
                                                         value="{{ p_attr_value.attribute_values__attribute_value }}">{{ p_attr_value.attribute_values__attribute_value }}</div>
                                                {% endif %}
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endfor %}
                    </ul>
                    <hr>
                    <button type="button" id="add-button" value="{{ product.id }}"
                            class="btn btn-success fw500">{% trans 'Add to basket' %}
                    </button>
                    <a href="{% url 'account:add_wash_list' product.product__id %}" class="btn btn-light fw500"
                       role="button"
                       aria-disabled="true">{% trans 'Add to Wish List' %}</a>
                </div>
            </div>
            <div class="col-md-7 col-lg-7 p-0">
                <div class="card mb-3 border-0">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-body p-1">
                                <h1 class="mb-0 h2 pe-4 pb-4">{{ product.product__name }}</h1>
                                <div class="bg-light">


                                    {% for image in product_image %}
                                        {% if image.is_feature %}
                                            <img class="img-fluid mx-auto d-block" width="200px"
                                                 src="{{ image.image.url }}" alt="{{ image.alt_text }}">
                                        {% else %}
                                            <img class="img-fluid d-block-inline pt-3" width="100px"
                                                 src="{{ image.image.url }}"
                                                 alt="{{ image.image.alt_text }}">
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <script>
        $(document).on('click', '#add-button', function (e) {
            e.preventDefault();
            {#url_product = window.location.href.split('?')[1]#}
            {#console.log(url_product)#}
            $.ajax({
                type: 'POST',
                url: '{% url "basket:basket_add" %}',
                data: {
                    product_id: $('#add-button').val(),
                    product_qty: $('#select option:selected').text(),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: 'post'
                },
                success: function (json) {
                    document.getElementById("basket-qty").innerHTML = json.qty
                },
                error: function (xhr, errmsg, err) {
                }
            });
        })
        {#    </script>#}
        {#        <script>#}
        var d = {}
        let textBoxes = document.querySelectorAll('[id^=target]')
        console.log(textBoxes)

        let e = 0
        let f = textBoxes.length

        for (let i in textBoxes) {
            if (e < f) {
                if (textBoxes[i].classList.contains("selected")) {
                    d[textBoxes[i].getAttribute('data-attribute')] = textBoxes[i].getAttribute('value')

                }
            } else {
                break
            }
            e++
            console.log(d)
        }

        $('[id^=target]').click(function () {
            const value = this.getAttribute('value');
            d[this.getAttribute('data-attribute')] = this.getAttribute('value')
            const querystring = buildUrlWithParams(d)
            const url = window.location.href.split('?')[0]
            window.location.href = url + "?" + querystring;
        });

        function buildUrlWithParams(data) {
            var searchparams = [];
            for (var d in data)
                searchparams.push(d + '=' + data[d]);
            return searchparams.join('&');
        }

    </script>
{% endblock %}