src/apps/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('register/verify_code/', views.UserRegisterVerifyCodeView.as_view(), name='verify'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    # reset password
    path('forget-password/', views.ForgettingPasswordView.as_view(), name='forget_password'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='reset_password'),
    path("reset-password-done/", views.ResetPasswordDoneView.as_view(), name='reset_password_done'),
    # dashboard
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('edit-profile/', views.EditProfileView.as_view(), name='edit_profile'),
    # Address
    path('addresses/', views.AddressView.as_view(), name='addresses'),
    path('addresses/add/', views.AddAddressView.as_view(), name='add_addresses'),
    path('addresses/edit/<uuid:id>/', views.EditAddressView.as_view(), name='edit_addresses'),
    path('addresses/delete/<uuid:id>/', views.DeleteAddressView.as_view(), name='delete_addresses'),
    path('addresses/set-default/<uuid:id>/', views.SetDefaultAddressView.as_view(), name='set_default_addresses'),
    # Wash list
    path('washlist/', views.WashListView.as_view(), name='wash_list'),
    path('washlist/add-to-washlist/<int:id>/', views.AddWashListView.as_view(), name='add_wash_list'),
    # orders
    path('orders/', views.UserOrders.as_view(), name='user_orders'),
]

src/apps/catalogue/urls.py
from django.urls import path

from . import views

app_name = 'catalogue'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product-detail/<str:web_id>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('category/<slug:slug>/', views.CategoryListView.as_view(), name='category'),
]

src/apps/checkout/urls.py
from django.urls import path

from . import views

app_name = 'checkout'

urlpatterns = [
    path('delivery-choices/', views.DeliveryChoicesView.as_view(), name='delivery_choices'),
    path('basket-update-delivery/', views.BasketUpdateDeliveryView.as_view(), name='basket_update_delivery'),
    path('delivery-address/', views.DeliveryAddressView.as_view(), name='delivery_address'),
    # path('payment-selection/', views.PaymentSelectionView.as_view(), name='payment_selection'),

]

src/apps/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('order-create/', views.CreateOrderView.as_view(), name='order_create'),
    path('payment-successfully/', views.PaymentSuccessfulView.as_view(), name='payment_success'),
    path('payment-selection/<int:order_id>/', views.PaymentSelectionView.as_view(), name='payment_selection'),
    path('apply-coupon/<int:order_id>/', views.ApplyCouponView.as_view(), name='apply_coupon'),
    path('delete-coupon/<int:order_id>/', views.RemoveCouponView.as_view(), name='delete_coupon'),

]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap

from apps.catalogue.sitemaps import StaticSitemapView, CategorySitemapView, ProductSitemapView

sitemaps = {
    'static': StaticSitemapView,
    'category': CategorySitemapView,
    'product': ProductSitemapView,
}

urlpatterns = [
    path('search/', include('apps.search.urls', namespace='search')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('robot.txt', include('robots.urls')),
    path('adminstartion@mohammadhssn78/', admin.site.urls),
    path('account/', include('apps.account.urls', namespace='account')),
    path('basket/', include('apps.basket.urls', namespace='basket')),
    path('checkout/', include('apps.checkout.urls', namespace='checkout')),
    path('oreders/', include('apps.orders.urls', namespace='orders')),
    path('', include('apps.catalogue.urls', namespace='catalogue')),

]

# if settings.DEBUG:
#     urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

src/apps/checkout/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class DeliveryOption(models.Model):
    """
        The Delivery methods table containing all delivery
    """

    DELIVERY_CHOICES = [
        ('IS', 'In Store'),
        ('HD', 'Home Delivery'),
        ('DD', 'Digital Delivery'),
    ]

    delivery_name = models.CharField(
        max_length=255,
        verbose_name=_('delivery_name'),
        help_text=_('format: required')
    )
    delivery_price = models.IntegerField(
        verbose_name=_('delivery price'),
        help_text=_('format:price Toman'),
        error_messages={
            'name': {
                'max_length': _('the price must be positive')
            },
        }
    )
    delivery_method = models.CharField(
        max_length=255,
        choices=DELIVERY_CHOICES,
        verbose_name=_('delivery_method'),
        help_text=_('format: required')
    )
    delivery_timeframe = models.CharField(
        max_length=255,
        verbose_name=_('delivery timeframe'),
        help_text=_('format: required')
    )
    delivery_window = models.CharField(
        max_length=255,
        verbose_name=_('delivery window'),
        help_text=_('format: required')
    )
    order = models.IntegerField(
        default=0,
        verbose_name=_('list order'),
        help_text=_('format: required')
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name=_('is_active'),
        help_text=_('in visible?')
    )

    class Meta:
        verbose_name = _("Delivery Option")
        verbose_name_plural = _("Delivery Options")

    def __str__(self):
        return self.delivery_name


class PaymentSelections(models.Model):
    """
        Store payment options
    """

    name = models.CharField(
        max_length=255,
        verbose_name=_('Name'),
        help_text=_('format: required')
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name=_('is_active'),
        help_text=_('in visible?')
    )

    class Meta:
        verbose_name = _("Payment Selection")
        verbose_name_plural = _("Payment Selections")

    def __str__(self):
        return self.name

src/apps/checkout/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from .models import DeliveryOption
from ..basket.basket import Basket
from apps.account.models import Address


class DeliveryChoicesView(LoginRequiredMixin, View):
    """
        show all delivery option if is_active=True
    """
    template_name = 'checkout/delivery_choices.html'

    def get(self, request):
        delivery_options = DeliveryOption.objects.filter(is_active=True)
        is_active_option = False
        if 'purchase' in request.session:
            is_active_option = request.session['purchase']['delivery_id']
        return render(request, self.template_name,
                      {'delivery_options': delivery_options, 'is_active_option': is_active_option})


class BasketUpdateDeliveryView(LoginRequiredMixin, View):
    """
        select delivery choices
        input: delivery_id from request POST
        get delivery_option with input(delivery_id) and update basket session with delivery_price
        and create or get session['purchase']
        output: return total price and delivery_price
    """

    def post(self, request):
        basket = Basket(request)
        delivery_option = int(request.POST.get('delivery_option'))
        delivery_type = get_object_or_404(DeliveryOption, id=delivery_option)
        update_total_price = basket.basket_update_delivery(delivery_type.delivery_price)

        session = request.session
        if 'purchase' not in request.session:
            session['purchase'] = {
                'delivery_id': delivery_type.id
            }
        else:
            session['purchase']['delivery_id'] = delivery_type.id
            session.modified = True

        response = JsonResponse({'total': update_total_price, 'delivery_price': delivery_type.delivery_price})
        return response


class DeliveryAddressView(LoginRequiredMixin, View):
    """
        Set address for delivery
        input: user must be login in site
        and session ['purchase'] exists.
        output: set address
    """

    template_name = 'checkout/delivery_address.html'

    def dispatch(self, request, *args, **kwargs):
        if 'purchase' not in request.session:
            messages.info(request, 'Please select delivery option', 'info')
            try:
                return redirect(request.META.get('HTTP_REFERER'))
            except TypeError:
                return redirect('catalogue:home')

        return super().dispatch(request, *args, **kwargs)

    def get(self, request):


        session = request.session
        addresses = Address.objects.filter(customer=request.user).order_by('-default')
        if addresses:
            if 'address' not in request.session:
                session['address'] = {'address_id': str(addresses[0].id)}
            else:
                session['address']['address_id'] = str(addresses[0].id)
                session.modified = True

        return render(request, self.template_name, {'addresses': addresses})

src/apps/checkout/templates/checkout/delivery_address.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans 'Delivery Address' %}{% endblock %}
{% block content %}

    <div class="container">
        <div class="col-12">
            <h1 class="h2">{% trans 'Delivery Address' %}</h1>
        </div>
        <div class="col-12">
            <p>{% trans 'Please select your delivery address' %}</p>
        </div>
        <hr/>
    </div>


    <div class="container">
        <div class="row g-3">
            {% if addresses|length == 0 %}
                <div class="col-12">{% trans 'There are no delivery addresses,' %} <a
                        href="{% url 'account:add_addresses' %}">{% trans 'add address' %}</a></div>
            {% else %}
                <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">

                    <div class="d-flex bd-highlight ms-0">
                        <div class="p-2 flex-grow-1 bd-highlight">{% trans 'Sub Total:' %}</div>
                        <div class="p-2 bd-highlight"><span class="fw-bold h5">T </span><span id="sub_total"
                                                                                              class="fw-bold h5">{{ basket.get_subtotal_price }}</span>
                        </div>
                    </div>
                    <div class="d-flex bd-highlight">
                        <div class="p-2 flex-grow-1 bd-highlight">{% trans 'Delivery Cost:' %}</div>
                        <div class="p-2 bd-highlight"><span class="fw-bold h5">T </span><span id="delivery_price"
                                                                                              class="fw-bold h5">{{ basket.get_delivery_price }}</span>
                        </div>
                    </div>
                    <div class="d-flex bd-highlight">
                        <div class="p-2 flex-grow-1 bd-highlight">{% trans 'Total:' %}</div>
                        <div class="p-2 bd-highlight"><span class="fw-bold h5">T </span><span id="total"
                                                                                              class="fw-bold h5">{{ basket.get_total_price }}</span>
                        </div>
                    </div>
                    <a role="button" href="{% url 'orders:order_create' %}" class="btn btn-success fw-bold w-100"
                       type="button">{% trans 'Pay Securely' %}</a>
                </div>

                <div class="col-md-7 col-lg-8">
                    {% for address in addresses %}
                        {% if not address.default %}
                            <h1 class="h5 pt-4">{% trans 'Other Addresses' %}</h1>
                        {% endif %}
                        <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{ option.id }}">
                            <div class="row g-0">
                                <div class="col">
                                    <div class="card pb-3 rounded-0">
                                        <div class="card-header bg-white small text-muted">
                                            {% if address.default %}
                                                {% trans 'Selected' %}
                                            {% endif %}
                                            &nbsp;
                                        </div>
                                        <div class="card-body small pb-1">
                                            <p class="card-text m-0 fw-bold">{{ address.full_name }}</p>
                                            <p class="card-text m-0">{{ address.address_line }}</p>
                                            <p class="card-text m-0">{{ address.address_line2 }}</p>
                                            <p class="card-text m-0">{{ address.town_city }}</p>
                                            <p class="card-text m-0">{{ address.postcode }}</p>
                                            <p class="card-text m-0">{% trans 'Phone number: ' %}{{ address.phone }}</p>
                                            <div class="pt-5">
                                                <a href="{% url 'account:edit_addresses' address.id %}"
                                                   class="text-decoration-none">{% trans 'Edit' %}</a>
                                                {% if not address.default %}
                                                    |<a href="{% url 'account:set_default_addresses' address.id %}"
                                                        class="text-decoration-none">{% trans 'Select' %}</a>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                    {#                                    </a>#}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

    </div>
{% endblock %}

src/apps/checkout/templates/checkout/delivery_choices.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Delivery Options' %}{% endblock %}
{% block content %}

    <div class="container">
        <div class="col-12">
            <h1 class="h2">{% trans 'Delivery Options' %}</h1>
        </div>
        <div class="col-12">
            <p>{% trans 'Select your delivery options' %}</p>
        </div>
        <hr/>
    </div>


    <div class="container">
        {#        {% if messages %}#}
        {#            <div class="alert alert-warning" alert-{{ message.tags }} role="alert">#}
        {#                {% for message in messages %}#}
        {#                    {{ message|safe }}#}
        {#                {% endfor %}#}
        {#            </div>#}
        {#        {% endif %}#}
        <div class="row g-3">
            {% if delivery_options|length == 0 %}
                <div class="col-12">{% trans 'There are no delivery options' %} <a
                        href="{% url 'catalogue:home' %}">{% trans 'Shop' %}</a>
                </div>
            {% else %}
                <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
                    <div class="d-flex bd-highlight ms-0">
                        <div class="p-2 flex-grow-1 bd-highlight">{% trans 'Sub Total:' %}</div>
                        <div class="p-2 bd-highlight"><span class="fw-bold h5">T </span><span id="sub_total"
                                                                                             class="fw-bold h5">{{ basket.get_subtotal_price }}</span>
                        </div>
                    </div>
                    <div class="d-flex bd-highlight">
                        <div class="p-2 flex-grow-1 bd-highlight">{% trans 'Delivery Cost:' %}</div>
                        <div class="p-2 bd-highlight"><span class="fw-bold h5">T </span><span id="delivery_price"
                                                                                             class="fw-bold h5">{{ basket.get_delivery_price }}</span>
                        </div>
                    </div>
                    <div class="d-flex bd-highlight">
                        <div class="p-2 flex-grow-1 bd-highlight">{% trans 'Total' %}:</div>
                        <div class="p-2 bd-highlight"><span class="fw-bold h5">T </span><span id="total"
                                                                                             class="fw-bold h5">{{ basket.get_total_price }}</span>
                        </div>
                    </div>
                    <a role="button" href="{% url 'checkout:delivery_address' %}" class="btn btn-success fw-bold w-100"
                       type="button">{% trans 'Pay Securely' %}</a>
                </div>
                <div class="col-md-7 col-lg-8">
                    {% for option in delivery_options %}
                        <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{ option.id }}">
                            <div class="row g-0">
                                <div class="col-md-2 ps-3 ps-md-4">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor"
                                         class="bi bi-truck mt-2"
                                         viewBox="0 0 16 16">
                                        <path
                                                d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"></path>
                                    </svg>
                                </div>
                                <div class="col-md-9 ps-md-1">
                                    <div class="card-body p-1">
                                        <p class="card-text ps-2 mb-1 pt-1 fw-bold">{{ option.delivery_name }}</p>
                                        <p class="card-text ps-2 pb-3">{% trans 'Your order should be delivered within' %}
                                            {{ option.delivery_timeframe }}</p>
                                    </div>
                                </div>
                                <div class="col-md-1 ps-md-1">
                                    <input class="align-middle h-100" type="radio"
                                            {% if is_active_option == option.id %} checked {% endif %}
                                           name="deliveryOption"
                                           id="{{ option.id }}"
                                           value="{{ option.id }}">
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>


    <script>
        $('input[type=radio][name=deliveryOption]').on('change', function (e) {
            e.preventDefault();
            $.ajax({
                type: "POST",
                url: '{% url "checkout:basket_update_delivery" %}',
                data: {
                    delivery_option: $(this).val(),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: "post",
                },
                success: function (json) {
                    document.getElementById("total").innerHTML = json.total;
                    document.getElementById("delivery_price").innerHTML = json.delivery_price;
                },
                error: function (xhr, errmsg, err) {
                },
            });

        });
    </script>


{% endblock %}