src/apps/basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.BasketSummaryView.as_view(), name='basket_summary'),
    path('basket-add/', views.BasketAddView.as_view(), name='basket_add'),
    path('basket-delete/', views.BasketDeleteView.as_view(), name='basket_delete'),
    path('basket-update/', views.BasketUpdateView.as_view(), name='basket_update'),
]

src/apps/catalogue/urls.py
from django.urls import path

from . import views

app_name = 'catalogue'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product-detail/<str:web_id>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('category/<slug:slug>/', views.CategoryListView.as_view(), name='category'),
]

src/apps/checkout/urls.py
from django.urls import path

from . import views

app_name = 'checkout'

urlpatterns = [
    path('delivery-choices/', views.DeliveryChoicesView.as_view(), name='delivery_choices'),
    path('basket-update-delivery/', views.BasketUpdateDeliveryView.as_view(), name='basket_update_delivery'),
    path('delivery-address/', views.DeliveryAddressView.as_view(), name='delivery_address'),
    # path('payment-selection/', views.PaymentSelectionView.as_view(), name='payment_selection'),

]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap

from apps.catalogue.sitemaps import StaticSitemapView, CategorySitemapView, ProductSitemapView

sitemaps = {
    'static': StaticSitemapView,
    'category': CategorySitemapView,
    'product': ProductSitemapView,
}

urlpatterns = [
    path('search/', include('apps.search.urls', namespace='search')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('robot.txt', include('robots.urls')),
    path('adminstartion@mohammadhssn78/', admin.site.urls),
    path('account/', include('apps.account.urls', namespace='account')),
    path('basket/', include('apps.basket.urls', namespace='basket')),
    path('checkout/', include('apps.checkout.urls', namespace='checkout')),
    path('oreders/', include('apps.orders.urls', namespace='orders')),
    path('', include('apps.catalogue.urls', namespace='catalogue')),

]

# if settings.DEBUG:
#     urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

src/apps/basket/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.http import JsonResponse

from .basket import Basket

from apps.catalogue.models import ProductInventory


class BasketSummaryView(View):
    """
        show all items in session basket in view
    """
    template_name = 'basket/basket_summary.html'

    def get(self, request):
        basket = Basket(request)

        return render(request, self.template_name, {'basket': basket})


class BasketAddView(View):
    """
        Add product in basket session
        input: product_id & product_qty from request POST
        and get product and send to basket method basket.add()
        output: sum quantity products
    """

    def post(self, request):
        basket = Basket(request)
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))
        product = get_object_or_404(ProductInventory, id=product_id)
        basket.add(product=product, qty=product_qty)
        basket_qty = basket.__len__()
        response = JsonResponse({'qty': basket_qty})
        return response


class BasketDeleteView(View):
    """
        Delete item form basket
        input: product_id from request POST
        and delete item form basket with method basket.delete()
        output: sum quantity products and total price items

    """

    def post(self, request):
        basket = Basket(request)
        product_id = int(request.POST.get('product_id'))
        basket.delete(product=product_id)

        basket_qty = basket.__len__()
        basket_total = basket.get_total_price()
        response = JsonResponse({'qty': basket_qty, 'subtotal': basket_total})
        return response


class BasketUpdateView(View):
    """
        update item form basket
        input: product_id & product_qty from request POST
        and update item form basket with method basket.update()
        output: sum quantity items and total price items

    """

    def post(self, request):
        basket = Basket(request)
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))
        basket.update(product=product_id, qty=product_qty)

        basket_qty = basket.__len__()
        basket_total = basket.get_subtotal_price()
        response = JsonResponse({'qty': basket_qty, 'subtotal': basket_total})
        return response

src/apps/basket/templates/basket/basket_summary.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Basket Summary' %}{% endblock %}
{% block content %}

    <div class="container">
        <div class="col-12">
            <h1 class="h2">{% trans 'Your Basket' %}</h1>
        </div>
        <div class="col-12">
            <p>{% trans 'Manage your' %} <b>{% trans 'items' %}</b>{% trans 'in your basket' %}
            </p>
        </div>
        <hr/>
    </div>
    <div class="container">
        <div class="row g-3">
            {% if basket|length == 0 %}
                <div class="col-12">{% trans 'Your basket is empty' %}<a
                        href="{% url 'catalogue:home' %}">{% trans 'Shop' %}</a></div>
            {% else %}
                <div class="col-12 bg-light p-3 d-flex justify-content-between">
                    <div class="d-flex d-flex-inline">
                        <div class="pe-3">{% trans 'Order' %}</div>
                        <div class="dropdown">
                            <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link"
                               id="dropdownLink"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                {% trans 'Shipping options' %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor"
                                     class="bi bi-chevron-down" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd"
                                          d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"></path>
                                </svg>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownLink">
                                <li class="item small">{% trans 'Next day delivery' %}</li>
                                <li class="item small">{% trans 'Premimum delivery' %}</li>
                            </ul>
                        </div>
                    </div>
                    <div class="text-end">
                        <div class="">{% trans 'Sub Total:' %} <span class="fw-bold"></span>
                            <div id="subtotal" class="d-inline-flex fw-bold">{{ basket.get_subtotal_price }} T</div>
                        </div>
{#                                                <div id="">{% trans 'Shipping' %} <span class="small">{% trans '(Next day delivery)' %}</span>:#}
{#                                                    <span#}
{#                                                            class="fw-bold">{% trans '£11.50' %}</span></div>#}
                        <div class="pt-2">{% trans 'Total to pay:' %} <span
                                class="fw-bold h5"></span><span id="total"
                                                                class="fw-bold h5">{{ basket.get_subtotal_price }} T</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
                    <div class="d-grid gap-2 ">
                        <a role="button" href="{% url 'checkout:delivery_choices' %}" class="btn btn-success fw-bold"
                           type="button">{% trans 'Checkout Securely' %}</a>
                        <button class="btn btn-light" type="button">{% trans 'Save for later' %}</button>
                    </div>
                </div>
                <div class="col-md-7 col-lg-8 p-0">
                    {% for item in basket %}
                        {% with product=item.product %}
                            <div class="card mb-3 border-0 product-item" data-index="{{ product.id }}">
                                <div class="row g-0">
                                    <div class="col-md-2 d-none d-md-block">
                                        {% for image in product.media_product_inventory.all %}
                                            {% if image.is_feature %}
                                                <img class="img-fluid" alt="Responsive image"
                                                     src="{{ image.image.url }}" alt="{{ image.alt_text }}">
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                    <div class="col-md-10 ps-md-3">
                                        <div class="card-body p-1">
                                            <a class="text-decoration-none text-reset"
                                               href="{{ item.product.product.get_absolute_url }}">
                                                <p class="card-text pb-3">{{ product.product.name }}</p>
                                            </a>
                                            <label for="select">Qty</label>
                                            <select id="select{{ product.id }}" style="width:50px;height:31px;">
                                                <option value="" selected disabled hidden>{{ item.qty }}</option>
                                                <option value="">1</option>
                                                <option value="">2</option>
                                                <option value="">3</option>
                                                <option value="">4</option>
                                            </select>
                                            <a type="button" id="update-button" data-index="{{ product.id }}"
                                               class="update-button text-decoration-none small ps-3">{% trans 'Update' %}</a>
                                            <a type="button" id="delete-button" data-index="{{ product.id }}"
                                               class="delete-button text-decoration-none small">{% trans 'Delete' %}</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endwith %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>

    <script>
        // Delete Item
        $(document).on("click", ".delete-button", function (e) {
            e.preventDefault();
            var prodid = $(this).data("index");
            $.ajax({
                type: "POST",
                url: '{% url "basket:basket_delete" %}',
                data: {
                    product_id: $(this).data("index"),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: "post",
                },
                success: function (json) {
                    $('.product-item[data-index="' + prodid + '"]').remove();

                    if (json.qty == 0) {
                        total = 0
                        subtotal = 0
                    } else {
                        total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
                        subtotal = json.subtotal
                    }

                    document.getElementById("subtotal").innerHTML = subtotal;
                    document.getElementById("basket-qty").innerHTML = json.qty;
                    document.getElementById("total").innerHTML = total;
                },
                error: function (xhr, errmsg, err) {
                },
            });
        });

        // Update Item
        $(document).on("click", ".update-button", function (e) {
            e.preventDefault();
            var prodid = $(this).data("index");
            $.ajax({
                type: "POST",
                url: '{% url "basket:basket_update" %}',
                data: {
                    product_id: $(this).data("index"),
                    product_qty: $("#select" + prodid + " option:selected").text(),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: "post",
                },
                success: function (json) {

                    {#total = (parseFloat(json.subtotal)).toFixed(2);#}
                    total = json.subtotal;
                    document.getElementById("basket-qty").innerHTML = json.qty;
                    document.getElementById("subtotal").innerHTML = json.subtotal;
                    document.getElementById("total").innerHTML = total;
                },
                error: function (xhr, errmsg, err) {
                },
            });
        });
    </script>

{% endblock %}