src/apps/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('register/verify_code/', views.UserRegisterVerifyCodeView.as_view(), name='verify'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    # reset password
    path('forget-password/', views.ForgettingPasswordView.as_view(), name='forget_password'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='reset_password'),
    path("reset-password-done/", views.ResetPasswordDoneView.as_view(), name='reset_password_done'),
    # dashboard
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('edit-profile/', views.EditProfileView.as_view(), name='edit_profile'),
    # Address
    path('addresses/', views.AddressView.as_view(), name='addresses'),
    path('addresses/add/', views.AddAddressView.as_view(), name='add_addresses'),
    path('addresses/edit/<uuid:id>/', views.EditAddressView.as_view(), name='edit_addresses'),
    path('addresses/delete/<uuid:id>/', views.DeleteAddressView.as_view(), name='delete_addresses'),
    path('addresses/set-default/<uuid:id>/', views.SetDefaultAddressView.as_view(), name='set_default_addresses'),
    # Wash list
    path('washlist/', views.WashListView.as_view(), name='wash_list'),
    path('washlist/add-to-washlist/<int:id>/', views.AddWashListView.as_view(), name='add_wash_list'),
    # orders
    path('orders/', views.UserOrders.as_view(), name='user_orders'),
]

src/apps/basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.BasketSummaryView.as_view(), name='basket_summary'),
    path('basket-add/', views.BasketAddView.as_view(), name='basket_add'),
    path('basket-delete/', views.BasketDeleteView.as_view(), name='basket_delete'),
    path('basket-update/', views.BasketUpdateView.as_view(), name='basket_update'),
]

src/apps/catalogue/urls.py
from django.urls import path

from . import views

app_name = 'catalogue'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product-detail/<str:web_id>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('category/<slug:slug>/', views.CategoryListView.as_view(), name='category'),
]

src/apps/search/urls.py
from django.urls import path

from . import views

app_name = 'search'

urlpatterns = [
    path('', views.SearchProductInventory.as_view(), name='search'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap

from apps.catalogue.sitemaps import StaticSitemapView, CategorySitemapView, ProductSitemapView

sitemaps = {
    'static': StaticSitemapView,
    'category': CategorySitemapView,
    'product': ProductSitemapView,
}

urlpatterns = [
    path('search/', include('apps.search.urls', namespace='search')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('robot.txt', include('robots.urls')),
    path('adminstartion@mohammadhssn78/', admin.site.urls),
    path('account/', include('apps.account.urls', namespace='account')),
    path('basket/', include('apps.basket.urls', namespace='basket')),
    path('checkout/', include('apps.checkout.urls', namespace='checkout')),
    path('oreders/', include('apps.orders.urls', namespace='orders')),
    path('', include('apps.catalogue.urls', namespace='catalogue')),

]

# if settings.DEBUG:
#     urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

src/templates/inc/footer.html
{% load i18n %}
<footer class="container py-5 footer">
    <hr>
    <div class="row pt-4">
        <div class="col-12 col-md">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                 class="bi bi-asterisk" viewBox="0 0 16 16">
                <path
                        d="M8 0a1 1 0 0 1 1 1v5.268l4.562-2.634a1 1 0 1 1 1 1.732L10 8l4.562 2.634a1 1 0 1 1-1 1.732L9 9.732V15a1 1 0 1 1-2 0V9.732l-4.562 2.634a1 1 0 1 1-1-1.732L6 8 1.438 5.366a1 1 0 0 1 1-1.732L7 6.268V1a1 1 0 0 1 1-1z"/>
            </svg>
            <small class="d-block mb-3 text-muted">&copy; 2017-2021</small>
        </div>
        <div class="col-6 col-md fs15">
            <h5>{% trans 'Features' %}</h5>
            <ul class="list-unstyled">
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Cool stuff' %}</a></li>
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Random feature' %}</a></li>
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Team feature' %}</a></li>
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Stuff for developers' %}</a></li>
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Another one' %}</a></li>
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Last time' %}</a></li>
            </ul>
        </div>
        <div class="col-6 col-md fs15">
            <h5>{% trans 'Resources' %}</h5>
            <ul class="list-unstyled">
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Resource name' %}</a></li>
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Resource' %}</a></li>
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Another resource' %}</a></li>
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Final resource' %}</a></li>
            </ul>
        </div>
        <div class="col-6 col-md fs15">
            <h5>{% trans 'Resources' %}</h5>
            <ul class="list-unstyled">
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Business' %}</a></li>
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Education' %}</a></li>
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Government' %}</a></li>
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Gaming' %}</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>{% trans 'About' %}</h5>
            <ul class="list-unstyled">
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Team' %}</a></li>
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Locations' %}</a></li>
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Privacy' %}</a></li>
                <li><a class="link-secondary text-decoration-none" href="#">{% trans 'Terms' %}</a></li>
            </ul>
        </div>
    </div>
</footer>

src/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

src/templates/inc/navbar.html
{% load i18n %}
<header class="pb-3">
    <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
        <div class="container-fluid px-md-4">
            <div class="d-flex w-100 navbar-collapse">
                <a class="navbar-brand d-flex-inline" href="/">
                    <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor"
                         class="bi bi-asterisk"
                         viewBox="0 0 16 16">
                        <path
                                d="M8 0a1 1 0 0 1 1 1v5.268l4.562-2.634a1 1 0 1 1 1 1.732L10 8l4.562 2.634a1 1 0 1 1-1 1.732L9 9.732V15a1 1 0 1 1-2 0V9.732l-4.562 2.634a1 1 0 1 1-1-1.732L6 8 1.438 5.366a1 1 0 0 1 1-1.732L7 6.268V1a1 1 0 0 1 1-1z"></path>
                    </svg>
                </a>
                <form class="d-flex w-45" action="{% url 'search:search' %}" method="get">
                    <input class="form-control me-1" required name="q" id="q" type="search"
                           placeholder="Search products"
                           aria-label="Search">
                    <button class="btn btn-outline-secondary" type="submit">{% trans 'Search' %}</button>
                </form>


                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle d-none d-md-block fw500" href="#" id="navbarDropdown"
                           role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {% trans 'All' %}
                            <i class="ps-1">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-chevron-down" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd"
                                          d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"></path>
                                </svg>
                            </i>
                        </a>

                        <ul class="dropdown-menu rounded-0 border-0" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'catalogue:home' %}">{% trans 'All' %}</a></li>

                            {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                    {% for children in c.children.all %}
                                        <a class="dropdown-item"
                                           href="{{ children.get_absolute_url }}">-------------->{{ children.name|title }}</a>
                                    {% endfor %}
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>

                <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                             class="bi bi-list"
                             viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                  d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"></path>
                        </svg>
                    </div>
                    <span class="fs15 fw500">{% trans 'Shop' %}</span>
                </button>
                <div>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent2">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-reset" href="#" id="navbarDropdown"
                                   role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    <div class="small text-muted">{% trans 'Hello,' %}
                                        {% if user.is_authenticated %}
                                            {{ request.user.phone_number }}
                                        {% else %}
                                            {% trans 'Login' %}
                                        {% endif %}
                                    </div>
                                    <span class="fs15 fw500">{% trans 'Account &amp; Lists' %}
                    </span>
                                </a>
                                <div class="dropdown-menu rounded-0" aria-labelledby="navbarDropdown">
                                    <div class="card border-0">
                                        <div class="card-body">
                                            <h6 class="card-title">{% trans 'My Account' %}</h6>
                                            <ul class="list-group list-group-flush dropdown-account-link">
                                                {% if user.is_authenticated %}
                                                    <a href="{% url 'account:dashboard' %}"
                                                       class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">{% trans 'Your Account' %}
                                                    </a>
                                                    <a href="{% url 'account:user_orders' %}"
                                                       class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">{% trans 'Orders' %}</a>
                                                    <a href="{% url 'account:logout' %}"
                                                       class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">{% trans 'Logout' %}</a>
                                                {% else %}
                                                    <a href="{% url 'account:register' %}"
                                                       class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">{% trans 'Register' %}</a>
                                                    <a href="{% url 'account:login' %}"
                                                       class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">{% trans 'Login' %}</a>
                                                {% endif %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <a type="button" role="button" href="{% url 'basket:basket_summary' %}"
                   class="btn btn-outline-secondary border-0 basket-btn">
                    {% with total_qty=basket|length %}
                        <div id="basket-qty" class="basket-qty">
                            {% if total_qty > 0 %}
                                {{ total_qty }}
                            {% else %}
                                0
                            {% endif %}
                        </div>
                    {% endwith %}
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                             class="bi bi-cart3"
                             viewBox="0 0 16 16">
                            <path
                                    d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"></path>
                        </svg>
                    </div>
                    <span class="fs15 fw500">{% trans 'Basket' %}</span>
                </a>
            </div>
            {#            <form class="d-flex w-45">#}
            {#                <input class="form-control me-1" type="search" placeholder="Search products or FAQ" aria-label="Search">#}
            {#                <button class="btn btn-outline-secondary" type="submit">{% trans 'Search' %}</button>#}
            {#            </form>#}
        </div>
    </nav>
</header>